SET timing ON
BEGIN 
 FOR i IN (SELECT table_name FROM  user_tables WHERE table_name='MAJESTIC') LOOP
 EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC ';
 END LOOP;
 END;
 /
 SET timing ON
BEGIN 
 FOR i IN (SELECT table_name FROM  user_tables WHERE table_name='MAJESTIC_INDEX1') LOOP
 EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC_INDEX1 ';
 END LOOP;
 END;
 /
 SET timing ON
BEGIN 
 FOR i IN (SELECT table_name FROM  user_tables WHERE table_name='MAJESTIC_INDEX2') LOOP
 EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC_INDEX2 ';
 END LOOP;
 END;
 /
 SET timing ON
BEGIN 
 FOR i IN (SELECT table_name FROM  user_tables WHERE table_name='MAJESTIC_INDEX3') LOOP
 EXECUTE IMMEDIATE 'DROP TABLE MAJESTIC_INDEX3 ';
 END LOOP;
 END;
 /